---
java_download_url: http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.tar.gz
java_archive_name: jdk-8u131-linux-x64.tar.gz
java_root_dir: /usr/share/java-1.8.0
java_jdk_dir: "{{ java_root_dir }}/jdk1.8.0_131"
elasticsearch_package_name: elasticsearch-5.6.3.rpm
elasticsearch_url: "https://artifacts.elastic.co/downloads/elasticsearch/{{ elasticsearch_package_name }}"
